name: Fmt

on:
  push:

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Clippy
      run: cargo clippy
    - name: Fmt
      run: cargo fmt --check

