name: lint

on:
  push:

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Fmt
      run: cargo fmt --check

