name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build test image
      run: docker build . -t test --target test
    - name: Run tests
      run: docker run test

